### ISSUE TITLE
Regex is not getting the right data

### ISSUE THREAD

**Issue by vitorarins** [igzivkov/tinyproxy_exporter#1]
I am getting an error because the regex is not getting any values from the page running Tinyproxy 1.8.4.

Here is the error:

```
Traceback (most recent call last):
  File "/tinyproxy_exporter", line 58, in <module>
    main()
  File "/tinyproxy_exporter", line 49, in main
    REGISTRY.register(TinyproxyCollector(args.s, args.t))
  File "/usr/lib/python3.6/site-packages/prometheus_client/core.py", line 50, in register
    names = self._get_names(collector)
  File "/usr/lib/python3.6/site-packages/prometheus_client/core.py", line 86, in _get_names
    for metric in desc_func():
  File "/tinyproxy_exporter", line 23, in collect
    yield GaugeMetricFamily('tinyproxy_connections_open', 'Number of open connections', values[0])
IndexError: list index out of range
```

**Comment by gmm42** [comment]
Thanks! It seems that hard-coded stats page is different from the stats.html template file. The updated regex should work with both now.
